apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: redis-build
    name: redis
  name: redis-build
spec:
  output:
    to:
      kind: ImageStreamTag
      name: redis:latest
  runPolicy: Serial
  source:
    contextDir: image
    git:
      uri: https://github.com/lany7/redis-openshift.git
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: rhel7:latest
        namespace: openshift
    type: Docker
